### ISSUE TITLE
ora_tablespace does not work for me

### ISSUE THREAD

**Issue by awegmann** [hajee/oracle#63]
I tried to increase the `system` tablespace on a Oracle XE. 
The puppet code look like this:

```
 ora_tablespace { 'SYSTEM@XE':
    ensure   => present,
    datafile => '/u01/app/oracle/oradata/XE/system.dbf',
    max_size => '1500M',
  }
```
The `ora_tablespace` type does not work for me. The error message is 
```
    Error: Could not prefetch ora_tablespace provider 'simple': Column BIG not found in results. Results contain FILE_NAME,SEGMENT_SPACE_MANA,BLOCK_SIZE,BYTES,CONTENTS,LOGGING,TABLESPACE_NAME,SID,AUTOEXTEN,MAX_SIZE,EXTENT_MANAGEMENT,INCREMENT_BY,BIGFILE
```

My first try was without the `datafile` attribute, but was the same result. Currently I'm testing this puppet manifest in a Vagrant VM with CentOS. I increased the log level to `debug` and `trace`. A `vagrant provision` on my environment gives the following output (I cut of the not so interesting log messages at the beginning):

```
==> default: Debug: Prefetching simple resources for ora_tablespace
==> default: Debug: executing select t.tablespace_name,
==> default:        t.logging,
==> default:        t.extent_management,
==> default:        t.segment_space_management,
==> default:        t.bigfile,
==> default:        f.file_name,
==> default:        t.contents,
==> default:        to_char(f.increment_by, '9999999999999999999') as increment_by,
==> default:        to_char(t.block_size, '9999999999999999999') as block_size,
==> default:        f.autoextensible,
==> default:        to_char(f.bytes, '9999999999999999999') as bytes,
==> default:        to_char(f.maxbytes, '9999999999999999999') as max_size
==> default: from   dba_tablespaces t, 
==> default:        dba_data_files f 
==> default: where  t.tablespace_name = f.tablespace_name
==> default:  on XE
==> default: Debug: Executing sql statement :
==> default:  select t.tablespace_name,
==> default:        t.logging,
==> default:        t.extent_management,
==> default:        t.segment_space_management,
==> default:        t.bigfile,
==> default:        f.file_name,
==> default:        t.contents,
==> default:        to_char(f.increment_by, '9999999999999999999') as increment_by,
==> default:        to_char(t.block_size, '9999999999999999999') as block_size,
==> default:        f.autoextensible,
==> default:        to_char(f.bytes, '9999999999999999999') as bytes,
==> default:        to_char(f.maxbytes, '9999999999999999999') as max_size
==> default: from   dba_tablespaces t, 
==> default:        dba_data_files f 
==> default: where  t.tablespace_name = f.tablespace_name
==> default: 
==> default: Debug: Executing sqlplus -S /nolog  command: @/tmp/command20150327-7125-4z8u9h-0.sql on XE as oracle, connected as sysdba
==> default: Debug: Executing 'su - oracle -c "export ORACLE_SID=XE;export ORAENV_ASK=NO;. oraenv; sqlplus -S /nolog  @/tmp/command20150327-7125-4z8u9h-0.sql"'
==> default: Error: Could not prefetch ora_tablespace provider 'simple': Column BIG not found in results. Results contain FILE_NAME,SEGMENT_SPACE_MANA,BLOCK_SIZE,BYTES,CONTENTS,LOGGING,TABLESPACE_NAME,SID,AUTOEXTEN,MAX_SIZE,EXTENT_MANAGEMENT,INCREMENT_BY,BIGFILE
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/helpers.rb:34:in `column_data'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/helpers.rb:33:in `fetch'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/helpers.rb:33:in `column_data'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/puppet/type/ora_tablespace/bigfile.rb:8:in `translate_to_resource'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/provider.rb:207:in `map_raw_to_resource'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/provider.rb:206:in `each'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/provider.rb:206:in `map_raw_to_resource'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/provider.rb:180:in `instances'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/provider.rb:179:in `map'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/provider.rb:179:in `instances'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/provider.rb:193:in `prefetch'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:277:in `prefetch'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:167:in `prefetch_if_necessary'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:67:in `evaluate'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:116:in `call'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:116:in `traverse'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:108:in `evaluate'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:164:in `apply'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util/log.rb:149:in `with_destination'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/report.rb:108:in `as_logging_destination'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:163:in `apply'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:125:in `apply_catalog'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:161:in `benchmark'
==> default: /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:160:in `benchmark'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:124:in `apply_catalog'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:192:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:268:in `apply_catalog'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:218:in `main'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:146:in `run_command'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:364:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:470:in `plugin_hook'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:364:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:478:in `exit_on_fail'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:364:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:137:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:91:in `execute'
==> default: /usr/bin/puppet:4
==> default: Debug: Executing sql statement :
==> default:  create   tablespace "SYSTEM"
==> default: Debug: Executing sqlplus -S /nolog  command: @/tmp/command20150327-7125-whopz2-0.sql on XE as oracle, connected as sysdba
==> default: Debug: Executing 'su - oracle -c "export ORACLE_SID=XE;export ORAENV_ASK=NO;. oraenv; sqlplus -S /nolog  @/tmp/command20150327-7125-whopz2-0.sql"'
==> default: Error: Execution of 'su - oracle -c "export ORACLE_SID=XE;export ORAENV_ASK=NO;. oraenv; sqlplus -S /nolog  @/tmp/command20150327-7125-whopz2-0.sql"' returned 151: ORACLE_BASE environment variable is not being set since this
==> default: information is not available for the current user ID oracle.
==> default: You can set ORACLE_BASE manually if it is required.
==> default: create	 tablespace "SYSTEM"
==> default:                            *
==> default: ERROR at line 1:
==> default: ORA-02199: missing DATAFILE/TEMPFILE clause
==> default: 
==> default: 
==> default: 
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util/execution.rb:188:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/sqlplus_command.rb:26:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/ora_command.rb:56:in `within_time'
==> default: /usr/lib/ruby/1.8/timeout.rb:67:in `timeout'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/ora_command.rb:55:in `within_time'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/sqlplus_command.rb:24:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/sqlplus_command.rb:35:in `execute_sql_command'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/sql.rb:22:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/oracle_access.rb:95:in `sql'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/command_entry.rb:25:in `send'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/command_entry.rb:25:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/blank_slate.rb:36:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/blank_slate.rb:35:in `each'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/blank_slate.rb:35:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/blank_slate.rb:34:in `each'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/blank_slate.rb:34:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/script_builder.rb:120:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/provider.rb:60:in `create'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/property/ensure.rb:16:in `set_present'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/property.rb:197:in `send'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/property.rb:197:in `call_valuemethod'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/property.rb:498:in `set'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/property.rb:581:in `sync'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:191:in `sync'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:128:in `sync_if_needed'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:81:in `perform_changes'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:20:in `evaluate'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:174:in `apply'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:187:in `eval_resource'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:117:in `call'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:117:in `evaluate'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:327:in `thinmark'
==> default: /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:326:in `thinmark'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:117:in `evaluate'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:118:in `traverse'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:108:in `evaluate'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:164:in `apply'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util/log.rb:149:in `with_destination'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/report.rb:108:in `as_logging_destination'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:163:in `apply'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:125:in `apply_catalog'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:161:in `benchmark'
==> default: /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:160:in `benchmark'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:124:in `apply_catalog'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:192:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:268:in `apply_catalog'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:218:in `main'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:146:in `run_command'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:364:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:470:in `plugin_hook'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:364:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:478:in `exit_on_fail'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:364:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:137:in `run'
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:91:in `execute'
==> default: /usr/bin/puppet:4
==> default: 
==> default: Error: /Stage[main]/Roles_ci::Profiles::Oracle/Ora_tablespace[SYSTEM@XE]/ensure: change from absent to present failed: Execution of 'su - oracle -c "export ORACLE_SID=XE;export ORAENV_ASK=NO;. oraenv; sqlplus -S /nolog  @/tmp/command20150327-7125-whopz2-0.sql"' returned 151: ORACLE_BASE environment variable is not being set since this
==> default: information is not available for the current user ID oracle.
==> default: You can set ORACLE_BASE manually if it is required.
==> default: create	 tablespace "SYSTEM"
==> default:                            *
==> default: ERROR at line 1:
==> default: ORA-02199: missing DATAFILE/TEMPFILE clause
==> default: 
==> default: 
==> default: 
==> default: Notice: /Stage[final]/Swarm::Service/Service[swarm]: Dependency Ora_tablespace[SYSTEM@XE] has failures: true
==> default: 
==> default: Debug: Finishing transaction 69887129252140
==> default: Debug: Storing state
==> default: Warning: /Stage[final]/Swarm::Service/Service[swarm]: Skipping because of failed dependencies
==> default: Debug: Stored state in 0.02 seconds
```

So it looks like parsing the result from the SQL command has some problems. When I execute the SELECT statement in DbVisualizer with this DB I get the following results:

```
TABLESPACE_NAME LOGGING EXTENT_MANAGEMENT SEGMENT_SPACE_MANAGEMENT BIGFILE FILE_NAME                               CONTENTS  INCREMENT_BY         BLOCK_SIZE           AUTOEXTENSIBLE BYTES                MAX_SIZE             
--------------- ------- ----------------- ------------------------ ------- --------------------------------------- --------- -------------------- -------------------- -------------- -------------------- -------------------- 
USERS           LOGGING LOCAL             AUTO                     NO      /u01/app/oracle/oradata/XE/users.dbf    PERMANENT                 1280                 8192 YES                       104857600          11811160064 
SYSAUX          LOGGING LOCAL             AUTO                     NO      /u01/app/oracle/oradata/XE/sysaux.dbf   PERMANENT                 1280                 8192 YES                       671088640          34359721984 
UNDOTBS1        LOGGING LOCAL             MANUAL                   NO      /u01/app/oracle/oradata/XE/undotbs1.dbf UNDO                       640                 8192 YES                        26214400          34359721984 
SYSTEM          LOGGING LOCAL             MANUAL                   NO      /u01/app/oracle/oradata/XE/system.dbf   PERMANENT                 1280                 8192 YES                       377487360            629145600 
```
Is it possible to change the `system` table space with the upper puppet code? It's again a lot of magic you do in your Ruby code ;-) so I would be happy to get a hint what to do. I even can try to fix the problem (maybe it's a Oracle XE issue again which does not happen on 'normal' Oracle) and provide you a pull request, but at the moment I don't know where to look at. 

Regards 
 Andreas

**Comment by hajee** [comment]
The message 

```
Column BIG not found in results. Results contain FILE_NAME,SEGMENT_SPACE_MANA,BLOCK_SIZE,BYTES,CONTENTS,LOGGING,TABLESPACE_NAME,SID,AUTOEXTEN,MAX_SIZE,EXTENT_MANAGEMENT,INCREMENT_BY,BIGFILE
```

Tells me that Puppet tries to get a column value from a record whith a column name of `BIG`, but it cannot find this column. It looks like the Oracle XE shows the full column name `BIGFILE`  while the EE version of Oracle truncates to `BIG`. 

Commit da89848050a8baa5b8b1944ff5d791141f83c4ff should fix this. Can you try it?

**Comment by awegmann** [comment]
Thanks a lot. I will try this today or tomorrow. Strange behaviour, that EE Oracle names the column "BIG" by itself.

**Comment by awegmann** [comment]
After adding other columns to the SELECT statement I now get the following log messages:

```
==> default: Debug: Executing sqlplus -S /nolog  command: @/tmp/command20150330-7158-1a4sl5f-0.sql on XE as oracle, connected as sysdba
==> default: Debug: Executing 'su - oracle -c "export ORACLE_SID=XE;export ORAENV_ASK=NO;. oraenv; sqlplus -S /nolog  @/tmp/command20150330-7158-1a4sl5f-0.sql"'
==> default: Notice: /Stage[main]/Roles_ci::Profiles::Oracle/Ora_tablespace[SYSTEM@XE]/size: size changed '377487360' to '1572864000'
==> default: Debug: Executing sql statement :
==> default:  alter tablespace "SYSTEM" resize 1572864000 
==> default: Debug: Executing sqlplus -S /nolog  command: @/tmp/command20150330-7158-1thouac-0.sql on XE as oracle, connected as sysdba
==> default: Debug: Executing 'su - oracle -c "export ORACLE_SID=XE;export ORAENV_ASK=NO;. oraenv; sqlplus -S /nolog  @/tmp/command20150330-7158-1thouac-0.sql"'
==> default: Error: /Stage[main]/Roles_ci::Profiles::Oracle/Ora_tablespace[SYSTEM@XE]: Could not evaluate: Execution of 'su - oracle -c "export ORACLE_SID=XE;export ORAENV_ASK=NO;. oraenv; sqlplus -S /nolog  @/tmp/command20150330-7158-1thouac-0.sql"' returned 5: ORACLE_BASE environment variable is not being set since this
==> default: information is not available for the current user ID oracle.
==> default: You can set ORACLE_BASE manually if it is required.
==> default: alter tablespace "SYSTEM" resize 1572864000
==> default: *
==> default: ERROR at line 1:
==> default: ORA-32773: operation not supported for smallfile tablespace SYSTEM
==> default: 
==> default: 
==> default: 
==> default: /usr/lib/ruby/site_ruby/1.8/puppet/util/execution.rb:188:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/sqlplus_command.rb:26:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/ora_command.rb:56:in `within_time'
==> default: /usr/lib/ruby/1.8/timeout.rb:67:in `timeout'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/ora_command.rb:55:in `within_time'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/sqlplus_command.rb:24:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/sqlplus_command.rb:35:in `execute_sql_command'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/sql.rb:22:in `execute'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/oracle/lib/ora_utils/oracle_access.rb:95:in `sql'
==> default: /tmp/vagrant-puppet/modules-23e45672cefa82348835335c4cc81070/easy_type/lib/easy_type/command_entry.rb:25:in `send'
```

As far as I understand, the problem is that the `SYSTEM` tablespace is a `SMALLFILE` type, which cannot be changed with an `ALTER TABLESPACE` in this way. So, `SMALLFILE` databases seems to be "traditional" and `BIGFILE` databases seem to be newer file type (I'm not a Oracle DBA, sorry). 

I found several other postings and blog entries for this topic and maybe I can do this with the following statement: 

```SQL
alter database datafile '/u01/app/oracle/oradata/XE/system.dbf' resize 1500M;
```

The official [Oracle documentations](http://docs.oracle.com/cd/B19306_01/server.102/b14220/physical.htm#i14068) explains the SYSTEM dataspaces are `SMALLFILE` by default.

> The system default is to create a smallfile tablespace, which is the traditional type of Oracle tablespace. The SYSTEM and SYSAUX tablespace types are always created using the system default type.

Maybe therefor the `ALTER TABLESPACE` will not work out-of-the-box changing these tablespaces. 

I'm not sure if I tell you something new. Would it be a good idea to issue different statements according to the type of the tablespace? Shall we try to add this functionality to `ora_tablespace`?

Regards
 Andreas

**Comment by hajee** [comment]
Andreas,

Your analysis is correct. 

> The SYSTEM tablespace is a SMALLFILE type, which cannot be changed with an ALTER TABLESPACE in this way

The philosophy we used while implementing the Puppet types for Oracle, is to let Oracle do the checks of what is allowed and what is not.  If we would implement all these checks into the types, the types would become very big while adding only limit extra value to its users. That's why we let Oracle notify you instead of us.

If you want to change the system tablespace, you can take a look at the `ora_database` type. This let's you create a database from scratch. Allowing you to tweak (almost) every setting there is for database creation.

Hope this helps.

Bert

**Comment by awegmann** [comment]
Hi Bert.

Thank you for your hint to `ora_database`. I will try to solve my problem with this. At the moment I use `ora_exec`, but this feels like a work around. Nevertheless my pull request is necessary for Oracle XE to be able to use `ora_tablespace` - if it is compatible with Oracle EE please accept the changes. (And please check the aliases if they are right).

I hope I will find the time in near future to run your integration test with beaker against my Oracle XE testbed - just to find out if there are more issues with the different Oracle versions. 

I think we can close this issue. 

*And again many thanks for your help and the fast answers to my questions.*

**Comment by hajee** [comment]
I will check your PR later. Yes you are right it is needed to get it working. It was always a bad idea to build on Oracle defaults.
